/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuditMonth {
  'id' : bigint,
  'status' : Status,
  'createdAt' : bigint,
  'monthName' : string,
}
export interface LoanEntry {
  'id' : bigint,
  'sNo' : bigint,
  'insuranceDone' : boolean,
  'insuranceApplicable' : boolean,
  'cersaiDone' : boolean,
  'loanType' : string,
  'cersaiApplicable' : boolean,
  'cersaiPendingReason' : string,
  'insurancePendingReason' : string,
  'auditMonthId' : bigint,
  'loanNumber' : string,
  'borrowerName' : string,
}
export interface LoanEntryStatus {
  'cersaiPending' : bigint,
  'insuranceCompleted' : bigint,
  'totalLoans' : bigint,
  'cersaiCompleted' : bigint,
  'insurancePending' : bigint,
}
export interface PendingLoanRow {
  'id' : bigint,
  'sNo' : bigint,
  'cersaiPending' : boolean,
  'cersaiPendingReason' : string,
  'insurancePendingReason' : string,
  'insurancePending' : boolean,
  'loanNumber' : string,
  'borrowerName' : string,
}
export type Status = { 'closed' : null } |
  { 'open' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoanEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      boolean,
      boolean,
      string,
      boolean,
      boolean,
      string,
    ],
    LoanEntry
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearLoansForMonth' : ActorMethod<[bigint], undefined>,
  'closeAuditMonth' : ActorMethod<[bigint], undefined>,
  'createAuditMonth' : ActorMethod<[string], AuditMonth>,
  'deleteLoanEntry' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMonthSummary' : ActorMethod<[bigint], LoanEntryStatus>,
  'getPendingLoans' : ActorMethod<[bigint], Array<PendingLoanRow>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAuditMonths' : ActorMethod<[], Array<AuditMonth>>,
  'listLoansByMonth' : ActorMethod<[bigint], Array<LoanEntry>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateLoanEntry' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      boolean,
      boolean,
      string,
      boolean,
      boolean,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];