/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoanEntry = IDL.Record({
  'id' : IDL.Nat,
  'sNo' : IDL.Nat,
  'insuranceDone' : IDL.Bool,
  'insuranceApplicable' : IDL.Bool,
  'cersaiDone' : IDL.Bool,
  'broughtForwardFromMonthId' : IDL.Nat,
  'broughtForwardFromMonthName' : IDL.Text,
  'loanType' : IDL.Text,
  'cersaiApplicable' : IDL.Bool,
  'cersaiPendingReason' : IDL.Text,
  'insurancePendingReason' : IDL.Text,
  'auditMonthId' : IDL.Nat,
  'loanNumber' : IDL.Text,
  'borrowerName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
export const AuditMonth = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'createdAt' : IDL.Int,
  'monthName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LoanEntryStatus = IDL.Record({
  'cersaiPending' : IDL.Nat,
  'insuranceApplicable' : IDL.Nat,
  'insuranceCompleted' : IDL.Nat,
  'totalLoans' : IDL.Nat,
  'cersaiApplicable' : IDL.Nat,
  'cersaiCompleted' : IDL.Nat,
  'insurancePending' : IDL.Nat,
});
export const PendingLoanRow = IDL.Record({
  'id' : IDL.Nat,
  'sNo' : IDL.Nat,
  'cersaiPending' : IDL.Bool,
  'broughtForwardFromMonthId' : IDL.Nat,
  'broughtForwardFromMonthName' : IDL.Text,
  'cersaiPendingReason' : IDL.Text,
  'insurancePendingReason' : IDL.Text,
  'insurancePending' : IDL.Bool,
  'loanNumber' : IDL.Text,
  'borrowerName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoanEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [LoanEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearLoansForMonth' : IDL.Func([IDL.Nat], [], []),
  'closeAuditMonth' : IDL.Func([IDL.Nat], [], []),
  'createAuditMonth' : IDL.Func([IDL.Text], [AuditMonth], []),
  'deleteAuditMonth' : IDL.Func([IDL.Nat], [], []),
  'deleteLoanEntry' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMonthSummary' : IDL.Func([IDL.Nat], [LoanEntryStatus], ['query']),
  'getPendingLoans' : IDL.Func([IDL.Nat], [IDL.Vec(PendingLoanRow)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAuditMonths' : IDL.Func([], [IDL.Vec(AuditMonth)], ['query']),
  'listLoansByMonth' : IDL.Func([IDL.Nat], [IDL.Vec(LoanEntry)], ['query']),
  'rolloverPendingLoans' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateLoanEntry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoanEntry = IDL.Record({
    'id' : IDL.Nat,
    'sNo' : IDL.Nat,
    'insuranceDone' : IDL.Bool,
    'insuranceApplicable' : IDL.Bool,
    'cersaiDone' : IDL.Bool,
    'broughtForwardFromMonthId' : IDL.Nat,
    'broughtForwardFromMonthName' : IDL.Text,
    'loanType' : IDL.Text,
    'cersaiApplicable' : IDL.Bool,
    'cersaiPendingReason' : IDL.Text,
    'insurancePendingReason' : IDL.Text,
    'auditMonthId' : IDL.Nat,
    'loanNumber' : IDL.Text,
    'borrowerName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const AuditMonth = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'createdAt' : IDL.Int,
    'monthName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LoanEntryStatus = IDL.Record({
    'cersaiPending' : IDL.Nat,
    'insuranceApplicable' : IDL.Nat,
    'insuranceCompleted' : IDL.Nat,
    'totalLoans' : IDL.Nat,
    'cersaiApplicable' : IDL.Nat,
    'cersaiCompleted' : IDL.Nat,
    'insurancePending' : IDL.Nat,
  });
  const PendingLoanRow = IDL.Record({
    'id' : IDL.Nat,
    'sNo' : IDL.Nat,
    'cersaiPending' : IDL.Bool,
    'broughtForwardFromMonthId' : IDL.Nat,
    'broughtForwardFromMonthName' : IDL.Text,
    'cersaiPendingReason' : IDL.Text,
    'insurancePendingReason' : IDL.Text,
    'insurancePending' : IDL.Bool,
    'loanNumber' : IDL.Text,
    'borrowerName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoanEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [LoanEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearLoansForMonth' : IDL.Func([IDL.Nat], [], []),
    'closeAuditMonth' : IDL.Func([IDL.Nat], [], []),
    'createAuditMonth' : IDL.Func([IDL.Text], [AuditMonth], []),
    'deleteAuditMonth' : IDL.Func([IDL.Nat], [], []),
    'deleteLoanEntry' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMonthSummary' : IDL.Func([IDL.Nat], [LoanEntryStatus], ['query']),
    'getPendingLoans' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(PendingLoanRow)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAuditMonths' : IDL.Func([], [IDL.Vec(AuditMonth)], ['query']),
    'listLoansByMonth' : IDL.Func([IDL.Nat], [IDL.Vec(LoanEntry)], ['query']),
    'rolloverPendingLoans' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateLoanEntry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };